# SQLite version 3.x
#   gem install sqlite3
development:
    adapter: postgresql
    encoding: utf8
    database: nannyworld_development
    username: postgres
    password: 
    host: localhost
    
    
test:
    adapter: postgresql
    encoding: utf8
    database: nannyworld_test
    username: postgres
    password: 
    host: localhost



